import Link from "next/link";
import "./styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-secondary">
        {children}
        <footer>
          <p className="text-center font-sm">
            Challenge by{" "}
            <Link
              href="https://www.frontendmentor.io?ref=challenge"
              target="_blank"
              className="text-link-color"
            >
              Frontend Mentor
            </Link>
            . Coded by{" "}
            <Link
              href="https://www.frontendmentor.io/profile/Donsmatt"
              className="text-link-color"
            >
              Collins Adaigho
            </Link>
            .
          </p>
        </footer>
      </body>
    </html>
  );
}
